### ISSUE TITLE
Z3 linked in the README is not a CAD software, but a SAT solver, a math software

### ISSUE THREAD

**Issue by yurivict** [open-tool-forge/fpga-toolchain#55] opened 2020-09-16 04:33 UTC
The README says:
```
Z3: Engine for SymbiYosys
```

**Comment by esden** [comment] 2020-09-16 04:56
Not sure what you are trying to say. But Z3, the SAT solver is indeed the correct tool. SymbiYosys is a formal verification tool, thus it uses a SAT solver engine...

**Comment by yurivict** [comment] 2020-09-16 05:02
So if SymbiYosys uses Z3 then it should depend on Z3. Z3 in itself has nothing to do with FPGA toolchains. Z3 is just a solver.

**Comment by esden** [comment] 2020-09-16 08:30
You are wrong about it. Z3 is one of the many SAT solver engines that SymbiYosys supports. It is important to say which exact engines are included in the toolchain, and this is the intention of the README listing. Formal verification just like simulation is very much part of FPGA toolchain. I am closing this issue as I am convinced that the initial topic of this issue is "as intended". The SAT library link is the correct this case. Cheers.

**Closed as completed by esden** 2020-09-16 08:30 UTC
